CREATE DATABASE IF NOT EXISTS mydb;

USE mydb;

CREATE TABLE IF NOT EXISTS uses(
    id INT AUTO_INCREMENT PRIMARY KEY.
    NAME VARCHAR(100) NOT NULL

)

INSERT INTO users(NAME) VALUES ("BINIT"),("ALINA"),("HAMAL");


